# Generated by stoatworks-unraid/scripts/gen-docker.mjs from fleet.json.
# Repo: srt-router. Edit fleet.json and regenerate — direct edits are overwritten.
#
# SRT Router — Rust service.
#
# NOTE: Built with default features. NDI is included but loads its runtime with
# dlopen at run time, so the image links no NDI SDK and ships no NDI runtime —
# the NDI transport is simply unavailable inside the container unless you
# mount a runtime yourself. The `omt` feature is left off deliberately: omt-io
# still links its SDK at build time, and that SDK is not redistributable.

FROM rust:1-slim AS builder
WORKDIR /app

# pkg-config and libssl-dev are not needed by the current dependency set (no
# openssl-sys in Cargo.lock), but cmake and a C toolchain are cheap insurance
# for transitive crates that build vendored C. Remove them if the build proves
# it does not need them.
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential cmake pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN cargo build --release -p srtrouter

FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=builder /app/target/release/srtrouter /usr/local/bin/srtrouter

EXPOSE 8080
EXPOSE 5001/udp
EXPOSE 5002/udp
EXPOSE 6001/udp
EXPOSE 6002/udp
VOLUME ["/app/state"]

COPY config/ /app/config-default/
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -fsS http://localhost:8080/ >/dev/null || exit 1

CMD ["srtrouter", "--config", "/app/config/srt-router.toml"]
