#!/bin/sh
# Generated by stoatworks-unraid/scripts/gen-docker.mjs from fleet.json.
# Repo: srt-router. Edit fleet.json and regenerate — direct edits are overwritten.
#
# Seeds /app/config from the image defaults the first time the container
# runs, then hands off to the real command.
#
# This exists because Unraid points /app/config at an appdata directory
# that does not exist yet on a first install. Docker creates it empty, and an
# empty bind mount hides whatever the image shipped at that path — so a config
# COPYed to /app/config at build time is missing precisely when it is
# first needed.

set -e

if [ -d /app/config-default ] && [ -z "$(ls -A /app/config 2>/dev/null)" ]; then
    echo "entrypoint: /app/config is empty, seeding defaults"
    mkdir -p /app/config
    cp -a /app/config-default/. /app/config/
    # Named for the app rather than left as example.toml, so the file the
    # command line points at is the file that is actually there.
    if [ -f /app/config/example.toml ] && \
       [ ! -f /app/config/srt-router.toml ]; then
        mv /app/config/example.toml /app/config/srt-router.toml
    fi
fi

exec "$@"
